universe = vanilla
executable = /afs/cern.ch/user/v/vpant/pprefanalysis/sub.sh
+JobFlavour           = "longlunch"
getenv     = True
requirements =((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
RequestCpus = 1
transfer_input_files  = voms_proxy.txt
environment = "X509_USER_PROXY=voms_proxy.txt"
arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_1.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_1.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_1.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_1.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_1.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_2.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_2.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_2.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_2.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_2.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_3.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_3.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_3.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_3.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_3.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_4.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_4.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_4.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_4.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_4.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_5.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_5.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_5.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_5.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_5.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_6.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_6.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_6.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_6.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_6.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_7.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_7.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_7.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_7.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_7.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_8.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_8.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_8.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_8.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_8.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_9.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_9.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_9.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_9.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_9.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_10.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_10.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_10.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_10.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_10.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_11.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_11.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_11.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_11.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_11.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_12.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_12.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_12.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_12.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_12.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_13.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_13.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_13.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_13.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_13.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_14.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_14.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_14.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_14.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_14.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_15.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_15.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_15.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_15.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_15.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_16.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_16.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_16.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_16.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_16.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_17.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_17.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_17.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_17.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_17.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_18.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_18.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_18.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_18.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_18.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_19.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_19.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_19.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_19.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_19.log
queue 

arguments             = input/ppref2024/20250209/pprefzerobiasplusforward2_set1_20.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set1_20.root 0 0
output                = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_20.out
error                 = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_20.err
log                   = condor/log/ppref2024/20250209/pprefzerobiasplusforward2_set1_20.log
queue 

