universe = vanilla
executable = /afs/cern.ch/user/v/vpant/pprefanalysis/sub.sh
+JobFlavour           = "longlunch"
getenv     = True
requirements =((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
RequestCpus = 1
transfer_input_files  = voms_proxy.txt
environment = "X509_USER_PROXY=voms_proxy.txt"
arguments             = input/ppref2024/20250313/Pythiapthat15_1.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_1.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_1.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_1.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_1.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_2.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_2.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_2.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_2.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_2.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_3.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_3.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_3.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_3.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_3.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_4.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_4.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_4.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_4.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_4.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_5.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_5.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_5.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_5.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_5.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_6.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_6.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_6.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_6.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_6.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_7.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_7.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_7.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_7.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_7.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_8.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_8.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_8.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_8.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_8.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_9.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_9.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_9.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_9.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_9.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_10.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_10.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_10.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_10.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_10.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_11.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_11.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_11.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_11.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_11.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_12.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_12.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_12.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_12.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_12.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_13.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_13.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_13.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_13.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_13.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_14.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_14.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_14.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_14.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_14.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_15.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_15.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_15.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_15.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_15.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_16.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_16.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_16.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_16.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_16.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_17.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_17.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_17.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_17.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_17.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_18.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_18.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_18.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_18.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_18.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_19.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_19.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_19.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_19.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_19.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_20.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_20.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_20.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_20.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_20.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_21.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_21.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_21.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_21.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_21.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_22.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_22.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_22.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_22.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_22.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_23.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_23.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_23.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_23.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_23.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_24.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_24.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_24.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_24.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_24.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_25.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_25.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_25.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_25.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_25.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_26.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_26.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_26.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_26.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_26.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_27.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_27.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_27.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_27.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_27.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_28.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_28.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_28.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_28.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_28.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_29.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_29.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_29.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_29.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_29.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_30.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_30.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_30.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_30.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_30.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_31.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_31.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_31.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_31.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_31.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_32.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_32.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_32.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_32.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_32.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_33.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_33.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_33.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_33.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_33.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_34.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_34.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_34.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_34.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_34.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_35.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_35.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_35.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_35.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_35.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_36.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_36.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_36.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_36.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_36.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_37.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_37.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_37.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_37.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_37.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_38.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_38.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_38.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_38.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_38.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_39.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_39.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_39.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_39.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_39.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_40.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_40.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_40.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_40.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_40.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_41.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_41.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_41.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_41.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_41.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_42.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_42.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_42.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_42.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_42.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_43.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_43.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_43.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_43.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_43.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_44.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_44.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_44.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_44.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_44.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_45.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_45.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_45.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_45.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_45.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_46.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_46.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_46.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_46.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_46.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_47.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_47.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_47.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_47.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_47.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_48.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_48.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_48.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_48.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_48.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_49.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_49.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_49.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_49.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_49.log
queue 

arguments             = input/ppref2024/20250313/Pythiapthat15_50.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/Pythiapthat15_50.root 1 0
output                = condor/log/ppref2024/20250313/Pythiapthat15_50.out
error                 = condor/log/ppref2024/20250313/Pythiapthat15_50.err
log                   = condor/log/ppref2024/20250313/Pythiapthat15_50.log
queue 

