universe = vanilla
executable = /afs/cern.ch/user/v/vpant/pprefanalysis/sub.sh
+JobFlavour           = "longlunch"
getenv     = True
requirements =((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
RequestCpus = 1
transfer_input_files  = voms_proxy.txt
environment = "X509_USER_PROXY=voms_proxy.txt"
arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_1.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_1.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_1.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_1.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_1.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_2.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_2.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_2.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_2.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_2.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_3.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_3.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_3.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_3.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_3.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_4.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_4.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_4.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_4.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_4.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_5.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_5.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_5.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_5.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_5.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_6.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_6.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_6.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_6.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_6.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_7.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_7.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_7.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_7.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_7.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_8.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_8.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_8.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_8.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_8.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_9.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_9.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_9.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_9.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_9.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_10.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_10.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_10.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_10.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_10.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_11.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_11.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_11.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_11.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_11.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_12.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_12.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_12.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_12.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_12.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_13.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_13.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_13.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_13.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_13.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_14.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_14.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_14.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_14.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_14.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_15.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_15.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_15.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_15.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_15.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_16.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_16.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_16.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_16.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_16.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_17.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_17.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_17.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_17.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_17.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_18.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_18.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_18.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_18.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_18.log
queue 

arguments             = input/ppref2024/20250210/pprefzerobiasplusforward2_set4_19.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward2_set4_19.root 0 0
output                = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_19.out
error                 = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_19.err
log                   = condor/log/ppref2024/20250210/pprefzerobiasplusforward2_set4_19.log
queue 

