universe = vanilla
executable = /afs/cern.ch/user/v/vpant/pprefanalysis/sub.sh
+JobFlavour           = "longlunch"
getenv     = True
requirements =((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
RequestCpus = 1
transfer_input_files  = voms_proxy.txt
environment = "X509_USER_PROXY=voms_proxy.txt"
arguments             = input/ppref2024/20250218/pprefzerobiasplusforward4_set2_1.txt /eos/user/v/vpant/ppref2024/ppref2024outputfiles/pprefzerobiasplusforward4_set2_1.root 0 0
output                = condor/log/ppref2024/20250218/pprefzerobiasplusforward4_set2_1.out
error                 = condor/log/ppref2024/20250218/pprefzerobiasplusforward4_set2_1.err
log                   = condor/log/ppref2024/20250218/pprefzerobiasplusforward4_set2_1.log
queue 

